### ISSUE TITLE
Outdated links

### ISSUE THREAD

**Issue by robingh42** [olininfo/olininfo.github.io#12]
There are a few outdated/broken links. For example: `https://rebeccasculinarygroup.com/olin/menu-items/` is the new DH website. Franks calendar does not work and the shop links should be added instead of just `tools.olin.edu`, if you need those links please feel free to email me.

**Comment by epan547** [comment]
Hi! DH links have been updated! Feel free to reply with the shop links + what we should label them as, and one of us will update those as well

**Comment by robingh42** [comment]
https://machineshop.olin.edu/
https://docs.google.com/spreadsheets/d/1jfob9gVYZZkCZc4wNg8JULbB30nOluEu7tC-GKFI4Do/edit?usp=sharing
https://docs.google.com/forms/d/e/1FAIpQLSc8yEJMZHmKemJrYusXco8RYSolG5GbxrFn1PmPaY8vJLHufA/viewform
https://outlook.office365.com/owa/calendar/ShopTest@olin.edu/bookings/
and there probably should be space for 3d printer forms and training signups (Next year)

**Comment by VagueSalutations** [comment]
Replaced the Tools tile with a Machine Shop tile and included all four links @robingh42 mentioned
